INSERT INTO PUBLISHER VALUES (1, 'MCGRAW-HILL', 9989076587, 'BANGALORE');
INSERT INTO PUBLISHER VALUES (2, 'PEARSON', 9889076565, 'NEWDELHI');
INSERT INTO PUBLISHER VALUES (3, 'RANDOM HOUSE', 7455679345, 'HYDRABAD');
INSERT INTO PUBLISHER VALUES (4, 'HACHETTE LIVRE', 8970862340, 'CHENAI');
INSERT INTO PUBLISHER VALUES(5, 'GRUPO PLANETA',7756120238,'BANGALORE');

INSERT INTO BOOK VALUES (1,'DBMS','JAN-2017', 1);
INSERT INTO BOOK VALUES (2,'ADBMS','JUN-2016', 1);
INSERT INTO BOOK VALUES (3,'CN','SEP-2016', 2);
INSERT INTO BOOK VALUES (4,'CG','SEP-2015', 5);
INSERT INTO BOOK VALUES (5,'OS','MAY-2016', 2);

INSERT INTO BOOK_AUTHORS VALUES (1, 1);
INSERT INTO BOOK_AUTHORS VALUES (1, 2);
INSERT INTO BOOK_AUTHORS VALUES (2, 3);
INSERT INTO BOOK_AUTHORS VALUES (3, 4);
INSERT INTO BOOK_AUTHORS VALUES (4, 5);

INSERT INTO AUTHOR VALUES (1, 'NAVATHE', NULL);
INSERT INTO AUTHOR VALUES (2, 'TANENBAUM', NULL);
INSERT INTO AUTHOR VALUES (3, 'EDWARD ANGEL', NULL);
INSERT INTO AUTHOR VALUES (4, 'GALVIN', NULL);

INSERT INTO LIBRARY_BRANCH VALUES (10,'RR NAGAR','BANGALORE');
INSERT INTO LIBRARY_BRANCH VALUES (11,'RNSIT','BANGALORE');
INSERT INTO LIBRARY_BRANCH VALUES (12,'RAJAJI NAGAR', 'BANGALORE');
INSERT INTO LIBRARY_BRANCH VALUES (13,'NITTE','MANGALORE');
INSERT INTO LIBRARY_BRANCH VALUES (14,'MANIPAL','UDUPI');

INSERT INTO BOOK_COPIES VALUES (10, 1, 10);
INSERT INTO BOOK_COPIES VALUES (5, 1,11);
INSERT INTO BOOK_COPIES VALUES (2, 2,12);
INSERT INTO BOOK_COPIES VALUES (5, 2,13);
INSERT INTO BOOK_COPIES VALUES (7, 3,14);
INSERT INTO BOOK_COPIES VALUES (1, 5,10);
INSERT INTO BOOK_COPIES VALUES (3, 4,11);

INSERT INTO CARD VALUES (100);
INSERT INTO CARD VALUES (101);
INSERT INTO CARD VALUES (102);
INSERT INTO CARD VALUES (103);
INSERT INTO CARD VALUES (104);